# Site settings
title: Merve Ozgul's Website
description: A blog on my projects and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://merveozgul.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Merve Ozgul
user_description: I'm a curious data-enthusiast who is passionate about innovation, entrepreneurial strategy and story-telling.I was born and raised in Istanbul, Turkey. 
user_title: Data Enthusiast | Business Analyst | Entrepreneur
email: mozgul2017@student.hult.edu
github_username:  merveozgul

# Google-analytics
google-analytics:
  id: "UA-134182587-1"

exclude: ['package.json', 'src' , 'node_modules']
