# Site settings
title: Merve Ozgul's Website
description: A blog on my projects and skills.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://merveozgul.github.io/" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Merve Ozgul
user_description: I'm a curious data-enthusiast who is passionate about innovation, entrepreneurial strategy and story-telling.I was born and raised in Istanbul, Turkey. Exploring new topics, cultures, food feed my soul.
I traveled more than 30 countries, met and collaborated with lots of different people. Experiencing diversity help me to understand how people think and how they communicate their needs. As entrepreneurship lies in my nature, I like to ideate solutions to the pain points and needs of the people, whether it is a social or business problem.
When finding a solution, I prefer to do quantitative analysis, to make the right decision and to be able to see mutliple scenarios clearly.
As data is at the heart of the quantitative analysis, I decided to learn about data science tools (R, Python, SQL). Theese tools combined with my
analytical mindset, help me to overcome challenges more effectively and leverage the story-telling by using interactive plots and dashboards.
If you are interested in my approach, please feel free to look at my projects!
 (I <span class="love">❤</span> Plotly!).
user_title: Data Enthusiast | Business Analyst | Econometrics
email: mozgul2017@student.hult.edu
github_username:  merveozgul

# Google-analytics
google-analytics:
  id: "UA-134182587-1"

exclude: ['package.json', 'src' , 'node_modules']
